alertFilters:
  - ruleId: 10049
    newRisk: FalsePositive
    url: http://127.0.0.1:8080
  - ruleId: 10049
    newRisk: FalsePositive
    url: http://127.0.0.1:8080/
  - ruleId: 10049
    newRisk: FalsePositive
    url: http://127.0.0.1:8080/robots.txt
  - ruleId: 10049
    newRisk: FalsePositive
    url: http://127.0.0.1:8080/sitemap.xml
